apiVersion: v1
kind: Pod
metadata:
  name: pod-multi
  namespace: tp2
  labels:
    app: multi-container-app
spec:
  containers:
    - name: nginx-container

      image: nginx:alpine
      ports:
        - containerPort: 80

    - name: busybox-container
      image: busybox
      env:
        - name: USER
          value: "root"
        - name: PASSWORD
          value: "123456"
      command: ["/bin/sh"]
      args: ["-c", "while true; do date; wget -qO- http://localhost:80; echo ''; sleep 10; done"]