name: Secret Demo Workflow

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Secret
        env:
          MY_KEY: ${{ secrets.API_KEY }} # Pega do cofre do GitHub
        run: |
          # O GitHub mascara automaticamente segredos, mas a boa prática é não dar echo neles.
          # Vamos apenas verificar se existe.
          if [ -n "$MY_KEY" ]; then
            echo "API_KEY configurado"
          else
            echo "API_KEY não encontrada"
          fi